import React from 'react'
import { Metadata } from 'next'
import Link from 'next/link'

/**
 * 定义页面元数据
 */
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const pages = [
  {
    name: '1. 并行路由',
    to:'/parallel'
  },
    {
    name: '2. 拦截路由',
    to:'/gallery'
  },
]

export default function Page() {
  return (
    <div className='flex flex-col gap-2'>
      {pages.map(v => {
        return (
          <Link href={v.to} key={v.to} className='hover:font-bold'>{ v.name }</Link>
        )
      })}
    </div>
  )
}
