import { Metadata } from 'next';
import React from 'react'

/**
 * 定义页面元数据
 */
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>首页</div>
  )
}
