import React from 'react'
import { Metadata } from 'next'
import { Button } from 'antd';

/**
 * 定义页面元数据
 */
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <div>首页</div>
      <Button type="primary">按钮</Button>
    </div>
  )
}
